### ISSUE TITLE
有时打开应用会立刻崩溃

### ISSUE THREAD

**Issue by 821938089** [YuKongA/Updater-KMP#33]
```
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class J.k0
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:5015)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4861)
	at android.os.Parcel.readValue(Parcel.java:4621)
	at android.os.Parcel.readValue(Parcel.java:4390)
	at android.os.Parcel.readListInternal(Parcel.java:5399)
	at android.os.Parcel.readArrayListInternal(Parcel.java:5418)
	at android.os.Parcel.readValue(Parcel.java:4651)
	at android.os.Parcel.readValue(Parcel.java:4390)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4488)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4447)
	at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:415)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:401)
	at android.os.BaseBundle.getValue(BaseBundle.java:381)
	at android.os.BaseBundle.getValue(BaseBundle.java:364)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.Bundle.getParcelableArrayList(Bundle.java:1046)
	at u0.M.a(Unknown Source:253)
	at u0.g1.l(Unknown Source:249)
	at R.a.l(Unknown Source:51)
	at J.d.a(Unknown Source:232)
	at u0.g1.l(Unknown Source:212)
	at R.a.l(Unknown Source:51)
	at J.d.I(Unknown Source:14)
	at J.q.p(Unknown Source:202)
	at J.v.k(Unknown Source:32)
	at J.A0.a(Unknown Source:43)
	at J.v.l(Unknown Source:8)
	at J.v.d(Unknown Source:2)
	at p.k0.m(Unknown Source:427)
	at u0.h1.d(Unknown Source:15)
	at u0.h1.c(Unknown Source:18)
	at androidx.lifecycle.u.a(Unknown Source:22)
	at androidx.lifecycle.v.a(Unknown Source:250)
	at p.k0.m(Unknown Source:398)
	at u0.q.onAttachedToWindow(Unknown Source:109)
	at android.view.View.dispatchAttachedToWindow(View.java:22334)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3544)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3551)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3551)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3508)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2933)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10224)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:1076)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1607)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NoSuchFieldException: CREATOR
	at java.lang.Class.getField(Class.java:2337)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4992)
	... 57 more
```

**Comment by YuKongA** [comment]
试试最新的 CI 还会不会崩溃

**Comment by 821938089** [comment]
试了下，打开了几次都没有发生崩溃了，应该是好了
